### ISSUE TITLE
Request to add SQL comments to Winston.config

### ISSUE THREAD

**Issue by slisowski** [usgs/winston#32]
With the new version of MySQL, the previous "grant" syntax that would create the Winston user either is deprecated or no longer works. 

I request that the following be added to the Winston.config in the distribution, so that users always know the current MySQL syntax to use to create the needed users, as Winston admins are sometimes not DBAs too.
<pre>
#   Syntax to execute as the root MySQL user to create the Winston user
#   Note: backticks ` vs straight single quotes ‘
# CREATE USER 'winstonuser'@'localhost' IDENTIFIED BY 'winstonpass';
# GRANT all on `W`.* to winstonuser@'localhost';
# GRANT all on `W%`.* to winstonuser@'localhost';
# flush privileges;
</pre>

**Comment by tparker-usgs** [comment]
Helpful SQL statements are in SQLnuggets.txt at the root directory of the distribution. 

Which version of MySQL deprecated the current syntax?

**Comment by slisowski** [comment]
Version 5.7.10 is the one that is giving me trouble. I came in and needed to fix one that someone else had set up, so I don't know what commands were executed before I came and tried running the grants with the "identified by", which failed, because the user existed, but without permissions.

**Comment by tparker-usgs** [comment]
Oracle reworked password security in MySQL 5.6. Versions 5.6 or later require the user to first set a password for the root user before creating other users. I have not encountered this behavior in recent versions of MariaDB.

In recent versions, when you attempt to create a user before setting a root password, MySQL returns:
ERROR 1820 (HY000): You must SET PASSWORD before executing this statement

To set the password: 
mysql> SET PASSWORD = PASSWORD('password');

I don't want to add SQL comments to Winston.config and I don't think the SQLnuggets file is the appropriate place since since this relates only to the installation of MySQL and not Winston tables or functionality. A better option is to include an install doc with winston. I've opened a new issue, #33, to cover that.
